export const AUTH_SERVICE = 'AUTH_SERVICE';
export const USER_SERVICE = 'USER_SERVICE';
export const PROJECTS_SERVICE = 'PROJECTS_SERVICE';
export const TASKS_SERVICE = 'TASKS_SERVICE';
export const COMMENTS_SERVICE = 'COMMENTS_SERVICE';
export const NOTIFICATIONS_SERVICE = 'NOTIFICATIONS_SERVICE';
